---
- hosts: WindowsServers
  roles:
    - ./ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: <IP address or Domain name>
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
